genre_mapping = {
    "International TV Shows, TV Dramas, TV Sci-Fi & Fantasy": "Fantasy & Sci-Fi",
    "Horror Movies, International Movies, Thrillers": "Horror",
    "Dramas, International Movies, Sports Movies": "Drama",
    "Comedies": "Comedy",
    "British TV Shows, Docuseries, Science & Nature TV": "Documentary",
    "Independent Movies, Thrillers": "Thriller",
    "Action & Adventure, Comedies": "Action & Adventure",
    "Dramas, Independent Movies, Romantic Movies": "Drama",
    "Comedies, International Movies, Romantic Movies": "Comedy",
    "Documentaries": "Documentary",
    "Anime Series, International TV Shows": "Animation",
    "Documentaries, International Movies, Music & Musicals": "Documentary",
    "Music & Musicals, Stand-Up Comedy": "Music & Musicals",
    "Comedies, Dramas, International Movies": "Comedy",
    "Stand-Up Comedy": "Stand-Up Comedy",
    "Kids' TV": "Children & Family",
    "TV Shows": "TV Shows",
    "Children & Family Movies": "Children & Family",
    "Children & Family Movies, Comedies": "Children & Family",
    "Classic Movies, Dramas, International Movies": "Drama",
    "Docuseries": "Documentary",
    "Documentaries, Faith & Spirituality": "Documentary",
    "Documentaries, International Movies, Sports Movies": "Documentary",
    "Docuseries, International TV Shows, Spanish-Language TV Shows": "Documentary",
    "Action & Adventure, Comedies, International Movies": "Action & Adventure",
    "Dramas, International Movies": "Drama",
    "Dramas, Independent Movies, International Movies": "Drama",
    "TV Comedies": "Comedy",
    "Movies": "Drama",
    "Dramas, Independent Movies, Sci-Fi & Fantasy": "Fantasy & Sci-Fi",
    "International TV Shows, Romantic TV Shows, Spanish-Language TV Shows": "Romance",
    "Comedies, Independent Movies, International Movies": "Comedy",
    "Dramas": "Drama",
    "Reality TV": "Reality TV",
    "TV Comedies, TV Dramas": "Comedy",
    "Action & Adventure, Classic Movies, Dramas": "Action & Adventure",
    "Action & Adventure, Dramas, International Movies": "Action & Adventure",
    "Crime TV Shows, International TV Shows, Reality TV": "Crime",
    "British TV Shows, TV Comedies": "Comedy",
    "Crime TV Shows, International TV Shows, TV Dramas": "Crime",
    "International TV Shows, TV Comedies": "Comedy",
    "Documentaries, Sports Movies": "Documentary",
    "Action & Adventure, Comedies, Dramas": "Action & Adventure",
    "British TV Shows, Docuseries, International TV Shows": "Documentary",
    "British TV Shows, Kids' TV": "Children & Family",
    "Dramas, Independent Movies, Thrillers": "Thriller",
    "Comedies, Romantic Movies": "Romance",
    "International Movies, Thrillers": "Thriller",
    "Action & Adventure": "Action & Adventure",
    "International TV Shows, Korean TV Shows, Romantic TV Shows": "Romance",
    "Docuseries, Science & Nature TV": "Documentary",
    "Dramas, Romantic Movies, Sports Movies": "Drama",
    "Crime TV Shows, Docuseries": "Crime",
    "Comedies, Independent Movies": "Comedy",
    "Comedies, International Movies, Music & Musicals": "Comedy",
    "Kids' TV, TV Action & Adventure, TV Sci-Fi & Fantasy": "Children & Family",
    "Crime TV Shows, TV Dramas, TV Thrillers": "Crime",
    "Documentaries, International Movies, LGBTQ Movies": "Documentary",
    "Dramas, Sports Movies": "Drama",
    "Dramas, Thrillers": "Thriller",
    "Romantic TV Shows, TV Dramas": "Romance",
    "Action & Adventure, Sci-Fi & Fantasy": "Fantasy & Sci-Fi",
    "British TV Shows, Crime TV Shows, International TV Shows": "Crime",
    "Dramas, Independent Movies": "Drama",
    "Action & Adventure, International Movies": "Action & Adventure",
    "Comedies, Dramas, Independent Movies": "Comedy",
    "Kids' TV, TV Comedies": "Children & Family",
    "Horror Movies, International Movies": "Horror",
    "Stand-Up Comedy & Talk Shows, TV Comedies": "Stand-Up Comedy",
    "Dramas, Romantic Movies": "Romance",
    "Action & Adventure, Independent Movies": "Action & Adventure",
    "Crime TV Shows, International TV Shows, Korean TV Shows": "Crime",
    "Classic Movies, Dramas, Romantic Movies": "Romance",
    "Dramas, International Movies, LGBTQ Movies": "Drama",
    "Comedies, LGBTQ Movies": "Comedy",
    "Horror Movies, Thrillers": "Horror",
    "British TV Shows, International TV Shows, Reality TV": "Reality TV",
    "Dramas, International Movies, Thrillers": "Thriller",
    "International TV Shows, Spanish-Language TV Shows, TV Dramas": "International",
    "International TV Shows, TV Comedies, TV Dramas": "International",
    "British TV Shows, International TV Shows, TV Dramas": "International",
    "Horror Movies, Independent Movies, Thrillers": "Horror",
    "Crime TV Shows, Romantic TV Shows, Spanish-Language TV Shows": "Crime",
    "Comedies, Dramas": "Comedy",
    "Children & Family Movies, Comedies, Dramas": "Children & Family",
    "Children & Family Movies, Dramas, Romantic Movies": "Children & Family",
    "Cult Movies, Horror Movies": "Horror",
    "Children & Family Movies, Dramas": "Children & Family",
    "Comedies, Dramas, Romantic Movies": "Romance",
    "Documentaries, LGBTQ Movies": "Documentary",
    "Kids' TV, TV Thrillers": "Children & Family",
    "Dramas, LGBTQ Movies, Romantic Movies": "Romance",
    "Anime Series, International TV Shows, Teen TV Shows": "Animation",
    "Classic Movies, Cult Movies, Horror Movies": "Horror",
    "Horror Movies, Sci-Fi & Fantasy, Thrillers": "Horror",
    "Anime Series, Crime TV Shows, TV Thrillers": "Animation",
    "Anime Series, TV Horror, TV Thrillers": "Animation",
    "Classic Movies, Dramas": "Drama",
    "British TV Shows, Crime TV Shows, Docuseries": "Crime",
    "Anime Series, Teen TV Shows": "Animation",
    "Dramas, International Movies, Romantic Movies": "Romance",
    "Dramas, Faith & Spirituality, International Movies": "Drama",
    "Comedies, International Movies, Sci-Fi & Fantasy": "Comedy",
    "TV Horror, TV Mysteries, Teen TV Shows": "Horror",
    "International TV Shows, TV Dramas": "International",
    "Action & Adventure, Dramas": "Action & Adventure",
    "Children & Family Movies, Classic Movies": "Children & Family",
    "TV Dramas, TV Sci-Fi & Fantasy": "Fantasy & Sci-Fi",
    "Comedies, Cult Movies, Dramas": "Comedy",
    "Reality TV, Teen TV Shows": "Reality TV",
    "Docuseries, Reality TV, Science & Nature TV": "Documentary",
    "Documentaries, Music & Musicals": "Documentary",
    "International TV Shows, Reality TV": "Reality TV",
    "Docuseries, Reality TV, Teen TV Shows": "Documentary",
    "Crime TV Shows, Docuseries, International TV Shows": "Crime",
    "Classic & Cult TV, TV Comedies": "Comedy",
    "International TV Shows, Korean TV Shows, Reality TV": "Reality TV",
    "Docuseries, Reality TV": "Documentary",
    "British TV Shows, International TV Shows, Romantic TV Shows": "Romance",
    "Comedies, Independent Movies, Thrillers": "Thriller",
    "International TV Shows, Korean TV Shows, TV Dramas": "International",
    "Anime Features": "Animation",
    "TV Horror, TV Mysteries, TV Sci-Fi & Fantasy": "Horror",
    "Children & Family Movies, Classic Movies, Comedies": "Children & Family",
    "Crime TV Shows, International TV Shows, TV Action & Adventure": "Crime",
    "Comedies, Faith & Spirituality, Romantic Movies": "Comedy",
    "Comedies, International Movies, Thrillers": "Thriller",
    "International Movies, Romantic Movies": "Romance",
    "Docuseries, International TV Shows, Science & Nature TV": "Documentary",
    "Classic Movies, Comedies, International Movies": "Comedy",
    "Action & Adventure, Horror Movies, Sci-Fi & Fantasy": "Action & Adventure",
    "British TV Shows, Docuseries": "Documentary",
    "Docuseries, International TV Shows": "Documentary",
    "Action & Adventure, Classic Movies": "Action & Adventure",
    "TV Dramas, TV Sci-Fi & Fantasy, TV Thrillers": "Fantasy & Sci-Fi",
    "Comedies, Sci-Fi & Fantasy": "Comedy",
    "Action & Adventure, Cult Movies, Dramas": "Action & Adventure",
    "Children & Family Movies, Comedies, Sci-Fi & Fantasy": "Children & Family",
    "International TV Shows, Spanish-Language TV Shows, TV Comedies": "International",
    "TV Action & Adventure, TV Dramas": "Action & Adventure",
    "Crime TV Shows, International TV Shows, Spanish-Language TV Shows": "Crime",
    "Kids' TV, Korean TV Shows": "Children & Family",
    "Action & Adventure, Independent Movies, International Movies": "Action & Adventure",
    "Children & Family Movies, Dramas, Sports Movies": "Children & Family",
    "International TV Shows, Romantic TV Shows, TV Comedies": "Romance",
    "TV Action & Adventure, TV Dramas, TV Sci-Fi & Fantasy": "Action & Adventure",
    "Dramas, Faith & Spirituality, Independent Movies": "Drama",
    "Docuseries, TV Comedies": "Documentary",
    "Dramas, Independent Movies, LGBTQ Movies": "Drama",
    "TV Dramas, TV Thrillers": "Thriller",
    "Action & Adventure, Dramas, Independent Movies": "Action & Adventure",
    "Independent Movies, Sci-Fi & Fantasy, Thrillers": "Thriller",
    "Thrillers": "Thriller",
    "Documentaries, Faith & Spirituality, Music & Musicals": "Documentary",
    "Dramas, Sci-Fi & Fantasy": "Fantasy & Sci-Fi",
    "Romantic TV Shows, TV Comedies": "Romance",
    "British TV Shows, International TV Shows, TV Comedies": "International",
    "British TV Shows, Kids' TV, TV Thrillers": "Children & Family",
    "Crime TV Shows, TV Dramas, TV Mysteries": "Crime",
    "Action & Adventure, International Movies, Romantic Movies": "Action & Adventure",
    "Action & Adventure, Romantic Movies": "Action & Adventure",
    "Horror Movies": "Horror",
    "International TV Shows, TV Dramas, TV Horror": "Horror",
    "British TV Shows, Classic & Cult TV, TV Comedies": "Comedy",
    "Crime TV Shows, TV Dramas": "Crime",
    "International TV Shows, Romantic TV Shows, TV Dramas": "Romance",
    "Children & Family Movies, Documentaries": "Children & Family",
    "Dramas, International Movies, Sports Movies": "Drama",
    "British TV Shows, Kids' TV, TV Comedies": "Children & Family",
    "Horror Movies, Independent Movies, International Movies": "Horror",
    "Horror Movies, Independent Movies, Sci-Fi & Fantasy": "Horror",
    "TV Sci-Fi & Fantasy, TV Thrillers": "Fantasy & Sci-Fi",
    "Horror Movies, Sci-Fi & Fantasy": "Horror",
    "International TV Shows, TV Horror, TV Thrillers": "Horror",
    "Romantic TV Shows, TV Comedies, TV Dramas": "Romance",
    "International TV Shows, Reality TV, Romantic TV Shows": "Reality TV",
    "Classic Movies, Dramas, Independent Movies": "Drama",
    "Romantic TV Shows, TV Dramas, Teen TV Shows": "Romance",
    "TV Action & Adventure, TV Comedies, TV Horror": "Action & Adventure",
    "TV Action & Adventure, TV Sci-Fi & Fantasy": "Action & Adventure",
    "Children & Family Movies, Comedies, Music & Musicals": "Children & Family",
    "British TV Shows, TV Horror, TV Thrillers": "Horror",
    "Independent Movies, International Movies, Thrillers": "Thriller",
    "Classic Movies, Cult Movies, Dramas": "Drama",
    "International Movies, Sports Movies": "Sports",
    "International TV Shows, TV Dramas, Teen TV Shows": "International",
    "Horror Movies, Independent Movies": "Horror",
    "International Movies": "International",
    "Anime Series, International TV Shows, TV Horror": "Animation",
    "Action & Adventure, International Movies, Sci-Fi & Fantasy": "Action & Adventure",
    "International TV Shows": "International",
    "Dramas, Music & Musicals, Sports Movies": "Drama",
    "Children & Family Movies, Dramas, International Movies": "Children & Family",
    "International TV Shows, Spanish-Language TV Shows, TV Action & Adventure": "International",
    "Dramas, International Movies, Music & Musicals": "Drama",
    "International Movies, Music & Musicals, Romantic Movies": "International",
    "Stand-Up Comedy & Talk Shows": "Stand-Up Comedy",
    "Anime Series, Kids' TV": "Animation",
    "Cult Movies, Dramas, International Movies": "Drama",
    "TV Action & Adventure, TV Comedies, TV Sci-Fi & Fantasy": "Action & Adventure",
    "TV Dramas": "Drama",
    "Children & Family Movies, Music & Musicals": "Children & Family",
    "Action & Adventure, International Movies, Music & Musicals": "Action & Adventure",
    "Action & Adventure, Documentaries, International Movies": "Action & Adventure",
    "Reality TV, Science & Nature TV": "Reality TV",
    "Dramas, Faith & Spirituality": "Drama",
    "Comedies, Horror Movies": "Comedy",
    "Action & Adventure, Anime Features, Children & Family Movies": "Action & Adventure",
    "Kids' TV, TV Action & Adventure": "Children & Family",
    "Children & Family Movies, Comedies, Romantic Movies": "Children & Family",
    "Kids' TV, TV Action & Adventure, TV Comedies": "Children & Family",
    "Anime Series, Crime TV Shows, International TV Shows": "Animation",
    "Docuseries, Spanish-Language TV Shows": "Documentary",
    "International TV Shows, TV Action & Adventure, TV Dramas": "International",
    "Kids' TV, Spanish-Language TV Shows, Teen TV Shows": "Children & Family",
    "Dramas, Horror Movies, Music & Musicals": "Drama",
    "Action & Adventure, Horror Movies": "Action & Adventure",
    "Crime TV Shows, Kids' TV": "Crime",
    "Classic & Cult TV, Kids' TV, TV Action & Adventure": "Children & Family",
    "Anime Series, Kids' TV, TV Action & Adventure": "Animation",
    "Anime Features, Children & Family Movies": "Animation",
    "Dramas, Horror Movies, Sci-Fi & Fantasy": "Drama",
    "International TV Shows, Korean TV Shows, Stand-Up Comedy & Talk Shows": "International",
    "International TV Shows, TV Action & Adventure, TV Sci-Fi & Fantasy": "International",
    "Dramas, Sci-Fi & Fantasy, Thrillers": "Fantasy & Sci-Fi",
    "Action & Adventure, Sci-Fi & Fantasy, Thrillers": "Action & Adventure",
    "Reality TV, Romantic TV Shows": "Reality TV",
    "Action & Adventure, Children & Family Movies, Sci-Fi & Fantasy": "Action & Adventure",
    "Action & Adventure, Children & Family Movies, Classic Movies": "Action & Adventure",
    "Children & Family Movies, Comedies, International Movies": "Children & Family",
    "Crime TV Shows, Kids' TV, TV Comedies": "Crime",
    "TV Action & Adventure": "Action & Adventure",
    "Dramas, International Movies, Sci-Fi & Fantasy": "Drama",
    "International TV Shows, Korean TV Shows, TV Action & Adventure": "International",
    "TV Comedies, TV Dramas, TV Horror": "Comedy",
    "British TV Shows, International TV Shows, Stand-Up Comedy & Talk Shows": "International",
    "Dramas, Music & Musicals, Sci-Fi & Fantasy": "Drama",
    "Spanish-Language TV Shows, TV Dramas": "International",
    "Documentaries, Stand-Up Comedy": "Documentary",
    "Action & Adventure, Dramas, Romantic Movies": "Action & Adventure",
    "Classic & Cult TV, TV Action & Adventure, TV Dramas": "Action & Adventure",
    "British TV Shows, TV Dramas, TV Sci-Fi & Fantasy": "Fantasy & Sci-Fi",
    "Music & Musicals": "Music & Musicals",
    "Anime Features, Music & Musicals": "Animation",
    "British TV Shows, Reality TV, Romantic TV Shows": "Reality TV",
    "Classic Movies, Comedies, Dramas": "Comedy",
    "Comedies, Independent Movies, Romantic Movies": "Comedy",
    "Action & Adventure, Independent Movies, Sci-Fi & Fantasy": "Action & Adventure",
    "Comedies, Cult Movies, Horror Movies": "Comedy",
    "Comedies, Cult Movies, Sports Movies": "Comedy",
    "International TV Shows, TV Dramas, TV Mysteries": "International",
    "Classic Movies, Documentaries": "Documentary",
    "Sci-Fi & Fantasy, Thrillers": "Fantasy & Sci-Fi",
    "Action & Adventure, Horror Movies, International Movies": "Action & Adventure",
    "Action & Adventure, Comedies, Cult Movies": "Action & Adventure",
    "Classic & Cult TV, Crime TV Shows, International TV Shows": "Crime",
    "British TV Shows, Romantic TV Shows, TV Dramas": "Romance",
    "Action & Adventure, Faith & Spirituality, Sci-Fi & Fantasy": "Action & Adventure",
    "TV Dramas, TV Sci-Fi & Fantasy, Teen TV Shows": "Fantasy & Sci-Fi",
    "Action & Adventure, Children & Family Movies": "Action & Adventure",
    "Comedies, Dramas, LGBTQ Movies": "Comedy",
    "Comedies, Horror Movies, Independent Movies": "Comedy",
    "Kids' TV, TV Comedies, TV Dramas": "Children & Family",
    "Crime TV Shows, International TV Shows, Romantic TV Shows": "Crime",
    "TV Action & Adventure, TV Dramas, TV Mysteries": "Action & Adventure",
    "Action & Adventure, Classic Movies, Cult Movies": "Action & Adventure",
    "TV Dramas, TV Horror, TV Mysteries": "Drama",
    "International Movies, Romantic Movies, Sci-Fi & Fantasy": "Romance",
    "Docuseries, International TV Shows, Reality TV": "Documentary",
    "Anime Series, Romantic TV Shows, Teen TV Shows": "Animation",
    "TV Action & Adventure, TV Horror, TV Sci-Fi & Fantasy": "Action & Adventure",
    "Anime Features, Music & Musicals, Sci-Fi & Fantasy": "Animation",
    "Action & Adventure, Anime Features, Classic Movies": "Action & Adventure",
    "Comedies, International Movies, LGBTQ Movies": "Comedy",
    "International TV Shows, Reality TV, Spanish-Language TV Shows": "Reality TV",
    "Anime Series, Romantic TV Shows": "Animation",
    "TV Comedies, TV Dramas, TV Mysteries": "Comedy",
    "International TV Shows, TV Action & Adventure, TV Mysteries": "International",
    "Docuseries, Science & Nature TV, TV Dramas": "Documentary",
    "International TV Shows, TV Dramas, TV Thrillers": "International",
    "Crime TV Shows, TV Action & Adventure, TV Thrillers": "Crime",
    "Anime Features, Children & Family Movies": "Animation",
    "Docuseries, TV Dramas": "Documentary",
    "Action & Adventure, Comedies, Sci-Fi & Fantasy": "Action & Adventure",
    "British TV Shows, International TV Shows, TV Action & Adventure": "International",
    "Children & Family Movies, Sports Movies": "Children & Family",
    "Comedies, Cult Movies, Independent Movies": "Comedy",
    "Children & Family Movies, Independent Movies": "Children & Family",
    "International TV Shows, TV Action & Adventure, TV Comedies": "International",
    "Action & Adventure, Horror Movies, Independent Movies": "Action & Adventure",
    "Action & Adventure, Classic Movies, Comedies": "Action & Adventure",
    "British TV Shows, Docuseries, TV Comedies": "Documentary",
    "Comedies, Documentaries": "Comedy",
    "British TV Shows, Classic & Cult TV, International TV Shows": "International",
    "TV Comedies, TV Sci-Fi & Fantasy": "Comedy",
    "TV Comedies, TV Sci-Fi & Fantasy, Teen TV Shows": "Comedy",
    "Documentaries, Dramas, International Movies": "Documentary",
    "TV Action & Adventure, TV Dramas, TV Horror": "Action & Adventure",
    "International TV Shows, TV Comedies, TV Sci-Fi & Fantasy": "International",
    "Action & Adventure, Classic Movies, International Movies": "Action & Adventure",
    "Anime Series": "Animation",
    "Cult Movies, Independent Movies, Thrillers": "Thriller",
    "Comedies, Independent Movies, Music & Musicals": "Comedy",
    "British TV Shows, Reality TV": "Reality TV",
    "TV Action & Adventure, TV Dramas, Teen TV Shows": "Action & Adventure",
    "Romantic TV Shows, TV Action & Adventure, TV Dramas": "Romance",
    "Crime TV Shows, TV Comedies": "Crime",
    "Crime TV Shows, TV Comedies, Teen TV Shows": "Crime",
    "Classic Movies, Cult Movies, Documentaries": "Documentary",
    "Children & Family Movies, Comedies, Cult Movies": "Children & Family",
    "Classic & Cult TV, Kids' TV, TV Comedies": "Children & Family",
    "Classic Movies, Dramas, LGBTQ Movies": "Drama",
    "Comedies, Romantic Movies, Sports Movies": "Comedy",
    "Kids' TV, Spanish-Language TV Shows": "Children & Family",
    "Action & Adventure, Children & Family Movies, Comedies": "Action & Adventure",
    "Reality TV, TV Comedies, TV Horror": "Reality TV",
    "Classic Movies, Dramas, Sports Movies": "Drama",
    "Kids' TV, TV Action & Adventure, TV Dramas": "Children & Family",
    "Action & Adventure, Sci-Fi & Fantasy, Sports Movies": "Action & Adventure",
    "Dramas, Romantic Movies, Thrillers": "Drama",
    "Action & Adventure, Cult Movies": "Action & Adventure",
    "Children & Family Movies, Dramas, Independent Movies": "Children & Family",
    "Children & Family Movies, Comedies, LGBTQ Movies": "Children & Family",
    "Action & Adventure, Comedies, Music & Musicals": "Action & Adventure",
    "Classic Movies, Horror Movies, Thrillers": "Horror",
    "Classic & Cult TV, TV Dramas, TV Sci-Fi & Fantasy": "Fantasy & Sci-Fi",
    "Children & Family Movies, Comedies, Sports Movies": "Children & Family",
    "Docuseries, Stand-Up Comedy & Talk Shows": "Documentary",
    "Action & Adventure, Dramas, Faith & Spirituality": "Action & Adventure",
    "TV Comedies, TV Horror, TV Thrillers": "Comedy",
    "Classic Movies, Comedies, Independent Movies": "Comedy",
    "Crime TV Shows, TV Horror, TV Mysteries": "Crime",
    "Children & Family Movies, Classic Movies, Dramas": "Children & Family",
    "Romantic TV Shows, Spanish-Language TV Shows, TV Comedies": "Romance",
    "Dramas, Faith & Spirituality, Sports Movies": "Drama",
    "Classic & Cult TV, TV Action & Adventure, TV Sci-Fi & Fantasy": "Action & Adventure",
    "Romantic TV Shows, TV Dramas, TV Sci-Fi & Fantasy": "Romance",
    "International TV Shows, Korean TV Shows, TV Horror": "International",
    "Classic Movies, Comedies, Romantic Movies": "Comedy",
    "Cult Movies, Horror Movies, Independent Movies": "Horror",
    "Classic Movies, Dramas, Thrillers": "Drama",
    "TV Dramas, TV Mysteries, TV Sci-Fi & Fantasy": "Fantasy & Sci-Fi",
    "Classic Movies, Independent Movies, Thrillers": "Thriller",
    "TV Comedies, TV Mysteries": "Comedy",
    "Kids' TV, TV Comedies, Teen TV Shows": "Children & Family",
    "Crime TV Shows, TV Action & Adventure, TV Sci-Fi & Fantasy": "Crime",
    "Kids' TV, TV Comedies, TV Sci-Fi & Fantasy": "Children & Family",
    "Anime Series, International TV Shows, Spanish-Language TV Shows": "Animation",
    "Cult Movies, Dramas, Thrillers": "Drama",
    "Docuseries, International TV Shows, Spanish-Language TV Shows": "Documentary",
    "Children & Family Movies, Faith & Spirituality": "Children & Family",
    "Classic Movies, Comedies, Sports Movies": "Comedy",
    "Comedies, Dramas, Sports Movies": "Comedy",
    "Action & Adventure, Dramas, Sports Movies": "Action & Adventure",
    "Kids' TV, Reality TV, TV Dramas": "Children & Family",
    "Horror Movies, LGBTQ Movies, Music & Musicals": "Horror",
    "Comedies, LGBTQ Movies, Music & Musicals": "Comedy",
    "Cult Movies, Documentaries, LGBTQ Movies": "Documentary",
    "International TV Shows, Romantic TV Shows, TV Action & Adventure": "Romance",
    "Children & Family Movies, Documentaries, Sports Movies": "Children & Family",
    "Action & Adventure, Romantic Movies, Sci-Fi & Fantasy": "Action & Adventure",
    "Classic & Cult TV, TV Sci-Fi & Fantasy": "Fantasy & Sci-Fi",
    "TV Action & Adventure, TV Mysteries, TV Sci-Fi & Fantasy": "Action & Adventure",
    "Children & Family Movies, Dramas, Music & Musicals": "Children & Family",
    "British TV Shows, Classic & Cult TV, Kids' TV": "Children & Family",
    "Docuseries, Science & Nature TV, TV Action & Adventure": "Documentary",
    "TV Dramas, TV Mysteries, TV Thrillers": "Drama",
    "Comedies, Cult Movies, LGBTQ Movies": "Comedy",
    "Crime TV Shows, International TV Shows, TV Sci-Fi & Fantasy": "Crime",
    "Comedies, Horror Movies, Sci-Fi & Fantasy": "Comedy",
    "Action & Adventure, Comedies, Horror Movies": "Action & Adventure",
    "Classic & Cult TV, Crime TV Shows, TV Dramas": "Crime",
    "TV Horror, Teen TV Shows": "Horror",
    "Action & Adventure, Documentaries, Sports Movies": "Action & Adventure",
    "Children & Family Movies, Documentaries, International Movies": "Children & Family",
    "International TV Shows, Reality TV, TV Comedies": "Reality TV",
    "Anime Features, International Movies, Sci-Fi & Fantasy": "Animation",
    "LGBTQ Movies, Thrillers": "LGBTQ+",
    "Classic Movies, Thrillers": "Thriller",
    "Documentaries, LGBTQ Movies, Music & Musicals": "Documentary",
    "Crime TV Shows, TV Dramas, TV Horror": "Crime",
    "Action & Adventure, Sports Movies": "Action & Adventure",
    "British TV Shows, Docuseries, Reality TV": "Documentary",
    "Crime TV Shows, Romantic TV Shows, TV Dramas": "Crime",
    "Kids' TV, Reality TV, Science & Nature TV": "Children & Family",
    "International TV Shows, Spanish-Language TV Shows, Stand-Up Comedy & Talk Shows": "International",
    "International TV Shows, TV Action & Adventure, TV Horror": "International",
    "Stand-Up Comedy & Talk Shows, TV Mysteries, TV Sci-Fi & Fantasy": "Stand-Up Comedy",
    "Kids' TV, Korean TV Shows, TV Comedies": "Children & Family",
    "International TV Shows, Romantic TV Shows": "Romance",
    "International TV Shows, Spanish-Language TV Shows, TV Horror": "International",
    "Comedies, Music & Musicals, Sports Movies": "Comedy",
    "Docuseries, TV Sci-Fi & Fantasy": "Documentary",
    "International Movies, LGBTQ Movies, Romantic Movies": "International",
    "Reality TV, Science & Nature TV, TV Action & Adventure": "Reality TV",
    "Dramas, Music & Musicals": "Drama",
    "Anime Features, International Movies": "Animation"
}
country_short = {
    "United States": "US",
    "India": "IN",
    "United Kingdom": "UK",
    "Canada": "CA",
    "France": "FR",
    "Spain": "ES",
    "Germany": "DE",
    "Japan": "JP",
    "South Korea": "KR",
    "Mexico": "MX",
    "Australia": "AU",
    "China": "CN",
    "Italy": "IT",
    "Brazil": "BR"
}
country_full = {
    "US": "United States",
    "IN": "India",
    "UK": "United Kingdom",
    "CA": "Canada",
    "FR": "France",
    "ES": "Spain",
    "DE": "Germany",
    "JP": "Japan",
    "KR": "South Korea",
    "MX": "Mexico",
    "AU": "Australia",
    "CN": "China",
    "IT": "Italy",
    "BR": "Brazil"
}
Major_genres = {

    "Fantasy & Sci-Fi": "Fantasy & Sci-Fi",
    "Horror": "Horror",
    "Comedy": "Comedy",
    "Documentary": "Documentary",
    "Thriller": "Thriller",
    "Action & Adventure": "Action & Adventure",
    "Drama": "Drama",
    "Animation": "Animation",
    "Music & Musicals": "Music & Musicals",
    "Stand-Up Comedy": "Stand-Up Comedy",
    "Children & Family": "Children & Family",
    "Comedies, International Movies": "Comedy",
    "Reality TV": "Reality TV",
    "Crime": "Crime",
    "Documentaries, International Movies": "Documentary",
    "Romance": "Romance",
    "International": "International",
    "TV Shows": "TV Shows",
    "Sports": "Sports",
    "Children & Family Movies, Sci-Fi & Fantasy": "Children & Family",
    "International Movies, Music & Musicals, Thrillers": "International",
    "Crime TV Shows, Spanish-Language TV Shows, TV Action & Adventure": "Crime",
    "Classic & Cult TV, Kids' TV, Spanish-Language TV Shows": "Children & Family",
    "Romantic TV Shows, Spanish-Language TV Shows, TV Dramas": "Romance",
    "Action & Adventure, Cult Movies, International Movies": "Action & Adventure",
    "International TV Shows, Romantic TV Shows, Teen TV Shows": "Romance",
    "Sports Movies": "Sports",
    "Action & Adventure, Children & Family Movies, Dramas": "Action & Adventure",
    "Dramas, Romantic Movies, Sci-Fi & Fantasy": "Drama",
    "Action & Adventure, Dramas, Sci-Fi & Fantasy": "Action & Adventure",
    "International TV Shows, TV Mysteries, TV Thrillers": "International",
    "Anime Series, International TV Shows, TV Thrillers": "Animation",
    "Comedies, Music & Musicals": "Comedy",
    "Horror Movies, International Movies, Sci-Fi & Fantasy": "Horror",
    "Comedies, Music & Musicals, Romantic Movies": "Comedy",
    "Children & Family Movies, Comedies, Faith & Spirituality": "Children & Family",
    "Action & Adventure, Anime Features, International Movies": "Action & Adventure",
    "Comedies, International Movies, Sports Movies": "Comedy",
    "TV Comedies, TV Dramas, Teen TV Shows": "Comedy",
    "Crime TV Shows, Docuseries, TV Mysteries": "Crime",
    "Crime TV Shows, Docuseries, Science & Nature TV": "Crime",
    "Action & Adventure, Anime Features, Sci-Fi & Fantasy": "Action & Adventure",
    "Crime TV Shows, Spanish-Language TV Shows, TV Dramas": "Crime",
    "Comedies, Cult Movies": "Comedy",
    "International TV Shows, Stand-Up Comedy & Talk Shows, TV Comedies": "International",
    "British TV Shows, Crime TV Shows, TV Dramas": "Crime",
    "Classic Movies, Comedies, Cult Movies": "Comedy",
    "International Movies, Romantic Movies, Thrillers": "International",
    "Classic Movies, Dramas, Music & Musicals": "Drama",
    "Cult Movies, Horror Movies, Thrillers": "Horror",
    "Anime Features, Romantic Movies": "Animation",
    "Dramas, Independent Movies, Sports Movies": "Drama",
    "Comedies, Dramas, Music & Musicals": "Comedy",
    "Anime Features, International Movies, Romantic Movies": "Animation",
    "Dramas, Independent Movies, Music & Musicals": "Drama",
    "Documentaries, Faith & Spirituality, International Movies": "Documentary",
    "Action & Adventure, Classic Movies, Sci-Fi & Fantasy": "Action & Adventure",
    "International TV Shows, Stand-Up Comedy & Talk Shows": "International",
    "Action & Adventure, Comedies, Independent Movies": "Action & Adventure",
    "British TV Shows, Kids' TV, TV Dramas": "Children & Family",
    "Classic & Cult TV, TV Action & Adventure, TV Horror": "Action & Adventure",
    "Children & Family Movies, Dramas, Faith & Spirituality": "Children & Family",
    "Dramas, LGBTQ Movies": "Drama",
    "TV Action & Adventure, TV Comedies": "Action & Adventure",
    "Action & Adventure, Anime Features, Horror Movies": "Action & Adventure",
    "Crime TV Shows, TV Comedies, TV Dramas": "Crime",
    "Classic Movies, Comedies, Music & Musicals": "Comedy",
    "Comedies, Horror Movies, International Movies": "Comedy",
    "International TV Shows, TV Horror, TV Mysteries": "Horror",
    "International Movies, Sci-Fi & Fantasy": "International",
    "Music & Musicals, Romantic Movies": "Music & Musicals",
    "Independent Movies": "Drama",
    "Crime TV Shows, International TV Shows, TV Mysteries": "Crime",
    "Action & Adventure, Thrillers": "Action & Adventure",
    "Comedies, Sports Movies": "Comedy",
    "TV Dramas, Teen TV Shows": "Drama",
    "Crime TV Shows, TV Action & Adventure, TV Dramas": "Crime",
    "Kids' TV, TV Dramas, Teen TV Shows": "Children & Family",
    "Anime Features, Children & Family Movies, International Movies": "Animation",
    "Anime Series, Crime TV Shows": "Animation",
    "Kids' TV, TV Dramas": "Children & Family",
    "British TV Shows, TV Comedies, TV Dramas": "Comedy",
    "TV Horror, TV Mysteries, TV Thrillers": "Horror",
    "International Movies, Music & Musicals": "International",
    "Crime TV Shows, TV Action & Adventure, TV Comedies": "Crime",
    "Action & Adventure, Children & Family Movies, Independent Movies": "Action & Adventure",
    "Crime TV Shows, International TV Shows, TV Comedies": "Crime",
    "TV Comedies, Teen TV Shows": "Comedy",
    "Reality TV, TV Horror, TV Thrillers": "Reality TV",
    "Documentaries, Horror Movies": "Documentary",
    "Classic & Cult TV, TV Horror, TV Mysteries": "Horror",
    "Crime TV Shows, TV Action & Adventure": "Crime",
    "Action & Adventure, Cult Movies, Sci-Fi & Fantasy": "Action & Adventure",
    "Anime Series, International TV Shows, Romantic TV Shows": "Animation",
    "Dramas, Music & Musicals, Romantic Movies": "Drama",
    "Action & Adventure, Comedies, Romantic Movies": "Action & Adventure",
    "Comedies, Dramas, Faith & Spirituality": "Comedy",
    "Romantic Movies": "Romance",
    "International TV Shows, Korean TV Shows, TV Comedies": "International",
    "Comedies, Independent Movies, LGBTQ Movies": "Comedy",
    "International Movies, Sci-Fi & Fantasy, Thrillers": "International",
    "Docuseries, Science & Nature TV, TV Comedies": "Documentary",
    "TV Comedies, TV Dramas, TV Sci-Fi & Fantasy": "Comedy",
    "Dramas, Faith & Spirituality, Romantic Movies": "Drama",
    "Reality TV, TV Comedies": "Reality TV",
    "LGBTQ+": "LGBTQ+",
    "Sci-Fi & Fantasy": "Fantasy & Sci-Fi"

}